
'use client';
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { Decal } from '@react-three/drei';

export function LaptopModel({ decalTexture }: { decalTexture?: any }) {
    const group = useRef<any>();
    useFrame((state) => {
        const t = state.clock.getElapsedTime();
        if (group.current) {
            group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 2) / 20 + 0.25, 0.1)
            group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 4) / 20, 0.1)
            group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 20, 0.1)
            group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t / 2)) / 2, 0.1)
        }
    });

    return (
        <group ref={group} dispose={null} scale={0.4}>
             <group rotation-x={-0.425} position={[0, -0.04, 0.41]}>
                <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh material-color="#292929" geometry={(nodes.Cube008 as any).geometry} material={(materials.alie as any)} />
                    <mesh material-color="#1f1f1f" geometry={(nodes.Cube008_1 as any).geometry} material={(materials.black as any)} />
                </group>
            </group>
            <mesh material-color="#1f1f1f" geometry={(nodes.keyboard as any).geometry} material={(materials.black as any)} position={[1.79, 0, 3.45]} rotation={[0, -0.16, 0]} />
            <group position={[0, -0.1, 3.39]}>
                <mesh material-color="#292929" geometry={(nodes.Cube002 as any).geometry} material={(materials.alie as any)} />
                <mesh material-color="#1f1f1f" geometry={(nodes.Cube002_1 as any).geometry} material={(materials.black as any)} />
            </group>
            <mesh material-color="#292929" geometry={(nodes.touchbar as any).geometry} material={(materials.touchbar as any)} position={[0, -0.03, 1.2]} />
            <mesh position={[0, -0.5, 0]}>
                <boxGeometry args={[4, 0.1, 2.8]} />
                <meshStandardMaterial color="#333" metalness={0.8} roughness={0.4} />
            </mesh>
            <mesh position={[0, 0.8, -1.35]} rotation={[1.4, 0, 0]}>
                <boxGeometry args={[4, 2.5, 0.1]} />
                <meshStandardMaterial color="#111" metalness={0.9} roughness={0.3} />
            </mesh>
             <mesh position={[0, 0.8, -1.3]} rotation={[1.4, 0, 0]}>
                <boxGeometry args={[3.8, 2.3, 0.1]} />
                <meshStandardMaterial color="black" />
            </mesh>
            <Decal position={[0, 0.25, 0]} rotation={0} scale={1.5} map={decalTexture} />
        </group>
    );
};
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: a.shevchuk (https://sketchfab.com/a.shevchuk)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/macbook-pro-2021-3771542f5c7847959a4cab69708f3353
title: MacBook Pro 2021
*/
useGLTF.preload('/scene.gltf')
const { nodes, materials } = useGLTF('/scene.gltf') as any;
